name: Build & Deploy Frontend to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: localhost:5000/skillswap-frontend:latest
      PUBLIC_IMAGE_NAME: registry.yungying.com/preflight-frontend:latest
      BUILD_DIR: ./skill-swap

    steps:
      - name: Discord notification (start)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: github_server
          DISCORD_AVATAR: https://picsum.photos/id/237/200/300
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has started GitHub Action."

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env to build folder
        run: cp /home/github-runner/actions-runner/frontend.env $BUILD_DIR/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Local Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_DIR }}
          load: true
          tags: ${{ env.IMAGE_NAME }}
          builder: default

      - name: Build and Push to Public Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_DIR }}
          no-cache: true
          push: true
          tags: ${{ env.PUBLIC_IMAGE_NAME }}
          builder: default

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Rollout Restart Frontend Deployment
        run: kubectl rollout restart deployment skillswap-frontend

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: https://fs-webhook.iecmu.com/hooks/redeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "project_group": "${{ vars.PROJECT_GROUP}}", "discord_webhook": "${{ secrets.DISCORD_WEBHOOK}}", "webhook_secret": "${{ secrets.WEBHOOK_SECRET }}" }'

      - name: Discord notification (finish)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: github_server
          DISCORD_AVATAR: https://picsum.photos/id/237/200/300
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has finished GitHub Action."
