name: Build & Deploy Frontend to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: localhost:5000/skillswap-frontend:latest
      PUBLIC_IMAGE_NAME: registry.yungying.com/preflight-frontend:latest
      BUILD_DIR: ./skill-swap

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env to build folder
        run: cp /home/github-runner/actions-runner/frontend.env $BUILD_DIR/.env

      - name: Set up Buildx Builder for Local
        uses: docker/setup-buildx-action@v3
        with:
          builder-name: localbuilder
          buildkitd-flags: --debug
          install: true

      - name: Build and Push to Local Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_DIR }}
          push: true
          tags: ${{ env.IMAGE_NAME }}
          builder: localbuilder

      - name: Set up Buildx Builder for Public
        uses: docker/setup-buildx-action@v3
        with:
          builder-name: publicbuilder

      - name: Build and Push to Public Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_DIR }}
          push: true
          tags: ${{ env.PUBLIC_IMAGE_NAME }}
          builder: publicbuilder
          buildkitd-flags: --debug
          install: true

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Rollout Restart Frontend Deployment
        run: kubectl rollout restart deployment skillswap-frontend
