name: Build & Deploy Frontend to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: localhost:5000/skillswap-frontend:latest
      PUBLIC_IMAGE_NAME: registry.yungying.com/skillswap-frontend:latest
      BUILD_DIR: ./skill-swap

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env to build folder
        run: cp /home/github-runner/actions-runner/frontend.env $BUILD_DIR/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Local Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_DIR }}
          push: true
          tags: ${{ env.IMAGE_NAME }}
          builder: default

      - name: Login to Public Registry
        uses: docker/login-action@v3
        with:
          registry: registry.yungying.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push to Public Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_DIR }}
          push: true
          tags: ${{ env.PUBLIC_IMAGE_NAME }}
          builder: default

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Rollout Restart Frontend Deployment
        run: kubectl rollout restart deployment skillswap-frontend
